features:
  - python stable
nginx:
  root: public_html/public
  passenger:
    enabled: "on"
    app_start_command: uvicorn main:app --port $PORT
commands:
  - pip install -r requirements.txt || pip install uvicorn