version: '3'

services:
  api:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - ./:/app
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - kortekstream-network

  # Jika ingin menambahkan Redis untuk caching
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - kortekstream-network
    volumes:
      - redis-data:/data
    restart: unless-stopped

networks:
  kortekstream-network:
    driver: bridge

volumes:
  redis-data: